alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
server:
  global:
    scrape_interval: 30s
    scrape_timeout: 10s
  service:
    type: NodePort
  ingress:
    enabled: true
    hosts:
    - prometheus.demoproject.info
