{
 "title": "HTTP(S) services checks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Endpoints status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sample_external_url_up{url=\"https://httpstat.us/200\", method=\"GET\"}",
     "legendFormat": "{{url}}"
    },
    {
     "expr": "sample_external_url_up{url=\"https://httpstat.us/503\", method=\"GET\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Response time (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sample_external_url_response_ms[5m])) by (method,path,url) / sum(irate(sample_external_url_response_ms_buckets_count[5m])) by (method,path,url)",
     "legendFormat": "{{method}} - {{url}}"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(sample_external_url_response_ms_buckets_bucket{le=\"1\"}[5m])) /  sum(irate(sample_external_url_response_ms_buckets_count[5m])) ) * 100",
     "legendFormat": "Duration < 1ms (%)"
    },
    {
     "expr": "( sum(irate(sample_external_url_response_ms_buckets_bucket{le=\"10\"}[5m])) /  sum(irate(sample_external_url_response_ms_buckets_count[5m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(sample_external_url_response_ms_buckets_bucket{le=\"100\"}[5m])) /  sum(irate(sample_external_url_response_ms_buckets_count[5m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    }
   ]
  }
 ]
}