service:
  type: NodePort
ingress:
  service:
    type: NodePort
  enabled: true
  hosts:
  - grafana.demoproject.info
env:
  GF_SERVER_ROOT_URL: "http://grafana.demoproject.info"
adminUser: admin
adminPassword: admin
